---
downloads: ~/.ansible-downloads/

user_name: "msnow"
user_email: "mikesnow79@gmail.com"
work_dirname: "projects"

# zsh_theme: "agnoster"
zsh_theme: "powerlevel9k/powerlevel9k"

editors:
  - vim
  - emacs
  - gimp

editors_aur: 
  - visual-studio-code-bin

utils:
  - base-devel
  - gconf
  - libcurl-gnutls
  - binutils
  - gcc
  - htop
  - make
  - mlocate
  - python-pip
  - xclip
  - xorg-xinput
  - ntp
  - fontforge
  - python-psutil
  - cmatrix
  - vlc

utils_aur:
    - git-extras
    - mkpasswd
    - zsh-git-prompt

shell_aliases:
    - alias ll='ls -lrta'
    - alias vi=vim

pip_packages: []

developer_stack: []

developer_stack_sudo:
    - nodejs
    - npm
    - jq
    - docker
    - docker-compose
    - hub

developer_stack_aur: []

fonts_aur:
  - ttf-input
  - ttf-blex-nerd-font-git
  - nerd-fonts-meslo

media: []

media_aur: []

vms:
  - virtualbox
  - vagrant

