---
downloads: ~/.ansible-downloads/

user_name: "msnow"
user_email: "mikesnow79@gmail.com"
work_dirname: "projects"

# zsh_theme: "agnoster"
zsh_theme: "powerlevel10k/powerlevel10k"

editors:
  - vim
  - emacs
  - gimp

editors_aur: 
  - visual-studio-code-bin

utils:
  - base-devel
  - gconf
  - libcurl-gnutls
  - binutils
  - gcc
  - htop
  - make
  - mlocate
  - python-pip
  - xclip
  - xorg-xinput
  - ntp
  - fontforge
  - python-psutil
  - cmatrix
  - vlc
  - bat
  - ranger
  - highlight
  - tldr
  - fd
  - tmux

utils_aur:
    - git-extras
    - mkpasswd
    - zsh-git-prompt

shell_aliases:
    - alias ll='ls -lrta'
    - alias vi=vim
    - alias cat=bat

pip_packages: 
  - pipenv

developer_stack: []

developer_stack_sudo:
    - nodejs
    - npm
    - jq
    - docker
    - docker-compose
    - hub

developer_stack_aur: []

fonts_aur:
  - ttf-input
  - ttf-blex-nerd-font-git
  - nerd-fonts-meslo

media: []

media_aur: []

browsers: 
  - firefox

browsers_aur: []

vms:
  - virtualbox
  - vagrant

uninstall_default_apps:
  - nano