---
downloads: ~/.ansible-downloads/

user_name: "msnow"
user_email: "mikesnow79@gmail.com"
work_dirname: "projects"

editors:
  - vim
  - emacs
  - gimp

editors_aur: 
  - visual-studio-code-bin

utils:
  - base-devel
  - gconf
  - libcurl-gnutls
  - binutils
  - gcc
  - htop
  - make
  - mlocate
  - python-pip
  - xclip
  - xorg-xinput
  - ntp

utils_aur:
    - git-extras
    - mkpasswd
    - zsh-git-prompt

shell_aliases:
    - alias ll='ls -lrta'
    - alias vi=vim

pip_packages: []

developer_stack:
    - nodejs
    - npm

developer_stack_sudo:
    - jq
    - docker
    - docker-compose
    - hub

developer_stack_aur: []

