---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
  - include_vars: "{{ item }}"
    with_fileglob:
      - "{{ playbook_dir }}/config.yml"
    tags: ['always']

  tasks:
    - name: Ensure Ansible downloads directory exists.
      file:
        path: "{{ downloads }}"
        state: directory

  roles:
    - { role: base,               tags: ['base'] }
    - { role: editors,            tags: ['editors'] }
    - { role: dev,                tags: ['dev'] }
    - { role: gnome,              tags: ['gnome']}

