---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
  - include_vars: "{{ item }}"
    with_fileglob:
      - "{{ playbook_dir }}/config.yml"
    tags: ['always']

  tasks:
    - name: What is downloads dir
      debug:
        msg: "downloads dir is {{ downloads }}"

    - name: Are eggs spam?
      debug:
        msg: "Egg value: {{ eggs }}"