- name: "keyboard Shortcuts - map caps to escape"
  dconf:
    key: "/org/gnome/desktop/input-sources/xkb-options"
    value: "['caps:escape']"
    state: present
  become_user: '{{ user_name }}'
  become: yes
