---
- name: Install browsers
  pacman:
    name: '{{ browsers }}'
    state: present
  become: yes

- name: Install browsers from Arch User Repository
  script: ../../../aur/install-aur.sh {{ item }}
  with_items: '{{ browsers_aur }}'
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255
  tags:
    - aur
