---
- name: Copy .vimrc to home
  copy:
    src: ../files/.vimrc
    dest: /home/{{ user_name }}/.vimrc
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0644
  become_user: '{{ user_name }}'
  become: yes