
---
- name: Install Utils
  pacman:
    name: '{{ utils }}'
    state: present
  become: yes

- name: Install Utils from Arch User Repository
  script: ../../../aur/install-aur.sh {{ item }}
  with_items: '{{ utils_aur }}'
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255
  tags:
    - aur

- include: ntp.yml
- include: pip.yml
- include: zsh.yml

- name: Creates projects directory
  file:
    path: /home/{{ user_name }}/{{ work_dirname }}
    state: directory
  become_user: '{{ user_name }}'
  become: yes

- include: git.yml